FROM php:8.2-apache

# Installer les dépendances nécessaires pour PostgreSQL + nettoyage
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Activer le module Apache rewrite
RUN a2enmod rewrite

# Activer AllowOverride pour .htaccess
RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

# Copier le code de votre projet (optionnel ici)
COPY . /var/www/html/